esphome:
  name: audioswitch
  platform: ESP32
  board: nodemcu-32s
  includes:
    - custom_audio_matrix.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Audioswitch"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

custom_component:
  - lambda: |-
      auto custom_audio_matrix = CustomAudioMatrix::instance();
      return {custom_audio_matrix};

switch:
  - platform: custom
    lambda: |-
      auto custom_audio_matrix = CustomAudioMatrix::instance();
      return custom_audio_matrix->switches;

    switches:
      - name: "Audio Switch 1->1"
      - name: "Audio Switch 1->2"
      - name: "Audio Switch 1->3"
      - name: "Audio Switch 2->1"
      - name: "Audio Switch 2->2"
      - name: "Audio Switch 2->3"
      - name: "Audio Switch 3->1"
      - name: "Audio Switch 3->2"
      - name: "Audio Switch 3->3"
