esphome:
  name: audioswitch
  platform: ESP32
  board: nodemcu-32s
  includes:
    - custom_audio_matrix.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Audioswitch"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

custom_component:
  - lambda: |-
      auto custom_audio_matrix = CustomAudioMatrix::instance();
      return {custom_audio_matrix};

switch:
  - platform: custom
    lambda: |-
      auto custom_audio_matrix = CustomAudioMatrix::instance();
      return {
        custom_audio_matrix->create_switch(1, 4),
        custom_audio_matrix->create_switch(1, 5),
        custom_audio_matrix->create_switch(3, 4),
        custom_audio_matrix->create_switch(3, 5),
        custom_audio_matrix->create_switch(5, 4),
        custom_audio_matrix->create_switch(5, 5),
        custom_audio_matrix->create_switch(7, 4),
        custom_audio_matrix->create_switch(7, 5)
      };

    switches:
      - name: "Audio Switch 1<-4"
      - name: "Audio Switch 1<-5"
      - name: "Audio Switch 3<-4"
      - name: "Audio Switch 3<-5"
      - name: "Audio Switch 5<-4"
      - name: "Audio Switch 5<-5"
      - name: "Audio Switch 7<-4"
      - name: "Audio Switch 7<-5"
