esphome:
  name: audioswitch
  platform: ESP32
  board: nodemcu-32s
  includes:
    - custom_audio_matrix.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Audioswitch"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: custom
    lambda: |-
      auto custom_audio_matrix = new CustomAudioMatrix();
      custom_audio_matrix->assign_mute_switch(7, out_7_mute);
      return {
        custom_audio_matrix->create_switch(7, 4),
        custom_audio_matrix->create_switch(7, 5)
      };

    switches:
      - name: "OUT 7 <- IN 4"
      - name: "OUT 7 <- IN 5"

  - platform: gpio
    id: out_7_mute
    name: Out 7 Mute
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23008_hub
      number: 0
      mode: OUTPUT
      inverted: true

i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 10kHz

mcp23008:
  - id: mcp23008_hub
    address: 0x20
